//
// Generated file, do not edit! Created by opp_msgc 4.4 from base/messages/control/command.msg.
//

#ifndef _TWSN_COMMAND_M_H_
#define _TWSN_COMMAND_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif


namespace twsn {

/**
 * Enum generated from <tt>base/messages/control/command.msg</tt> by opp_msgc.
 * <pre>
 * enum CmdLevel {
 *     UNKNOWN = 0;
 *     PHYS = 1;
 *     LINK = 2;
 *     NETW = 3;
 *     TRAN = 4;
 *     APPL = 5;
 * };
 * </pre>
 */
enum CmdLevel {
    UNKNOWN = 0,
    PHYS = 1,
    LINK = 2,
    NETW = 3,
    TRAN = 4,
    APPL = 5
};

/**
 * Enum generated from <tt>base/messages/control/command.msg</tt> by opp_msgc.
 * <pre>
 * enum CmdID {
 *     
 *     CMD_DATA_NOTI = 0; 
 *     CMD_DATA_FETCH = 1; 
 *     CMD_READY = 2; 
 *     
 *     
 *     CMD_PHY_PD = 10; 
 *     CMD_PHY_IDLE = 11; 
 *     CMD_PHY_RX = 12; 
 *     CMD_PHY_TX = 13; 
 *     CMD_PHY_CCA = 14; 
 *     
 *     
 *     CMD_LIN_CCA_RESULT = 20; 
 * };
 * </pre>
 */
enum CmdID {
    CMD_DATA_NOTI = 0,
    CMD_DATA_FETCH = 1,
    CMD_READY = 2,
    CMD_PHY_PD = 10,
    CMD_PHY_IDLE = 11,
    CMD_PHY_RX = 12,
    CMD_PHY_TX = 13,
    CMD_PHY_CCA = 14,
    CMD_LIN_CCA_RESULT = 20
};

/**
 * Class generated from <tt>base/messages/control/command.msg</tt> by opp_msgc.
 * <pre>
 * message Command {
 *     
 *     
 *     
 *     int src = UNKNOWN;
 *     int des = UNKNOWN;
 *     
 *     int cmdId;
 * }
 * </pre>
 */
class Command : public ::cMessage
{
  protected:
    int src_var;
    int des_var;
    int cmdId_var;

  private:
    void copy(const Command& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Command&);

  public:
    Command(const char *name=NULL, int kind=0);
    Command(const Command& other);
    virtual ~Command();
    Command& operator=(const Command& other);
    virtual Command *dup() const {return new Command(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSrc() const;
    virtual void setSrc(int src);
    virtual int getDes() const;
    virtual void setDes(int des);
    virtual int getCmdId() const;
    virtual void setCmdId(int cmdId);
};

inline void doPacking(cCommBuffer *b, Command& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Command& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>base/messages/control/command.msg</tt> by opp_msgc.
 * <pre>
 * message CmdCCA extends Command {
 *     src = LINK;
 *     des = PHYS;
 *     cmdId = CMD_PHY_CCA;
 *     double duration = 0.000128; 
 * }
 * </pre>
 */
class CmdCCA : public ::twsn::Command
{
  protected:
    double duration_var;

  private:
    void copy(const CmdCCA& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CmdCCA&);

  public:
    CmdCCA(const char *name=NULL, int kind=0);
    CmdCCA(const CmdCCA& other);
    virtual ~CmdCCA();
    CmdCCA& operator=(const CmdCCA& other);
    virtual CmdCCA *dup() const {return new CmdCCA(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual double getDuration() const;
    virtual void setDuration(double duration);
};

inline void doPacking(cCommBuffer *b, CmdCCA& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, CmdCCA& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>base/messages/control/command.msg</tt> by opp_msgc.
 * <pre>
 * message CmdCCAR extends Command {
 *     src = PHYS;
 *     des = LINK;
 *     cmdId = CMD_LIN_CCA_RESULT;
 *     bool clearChannel;
 * }
 * </pre>
 */
class CmdCCAR : public ::twsn::Command
{
  protected:
    bool clearChannel_var;

  private:
    void copy(const CmdCCAR& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CmdCCAR&);

  public:
    CmdCCAR(const char *name=NULL, int kind=0);
    CmdCCAR(const CmdCCAR& other);
    virtual ~CmdCCAR();
    CmdCCAR& operator=(const CmdCCAR& other);
    virtual CmdCCAR *dup() const {return new CmdCCAR(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual bool getClearChannel() const;
    virtual void setClearChannel(bool clearChannel);
};

inline void doPacking(cCommBuffer *b, CmdCCAR& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, CmdCCAR& obj) {obj.parsimUnpack(b);}

}; // end namespace twsn

#endif // _TWSN_COMMAND_M_H_
